# Generated by Django 3.1.4 on 2020-12-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='cliente_fotos'),
        ),
    ]
