# Generated by Django 3.1.4 on 2021-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20201228_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(upload_to='cliente_fotos'),
        ),
    ]
